import type { Rule, RuleResult } from '../rule-registry'
import type { ComponentNode, PerformanceMetrics } from '../types'

/**
 * Returns true when `value` is a string representation of a non-negative integer.
 * Only non-negative integers are generated by `key={index}` in React.
 */
function isNonNegativeIntegerString(value: unknown): boolean {
  if (typeof value !== 'string') return false
  if (value === '') return false
  // Must consist entirely of digits (no sign, no decimal, no whitespace)
  if (!/^\d+$/.test(value)) return false
  return true
}

/**
 * Rule: index-as-key
 * SOT Section 12, 7
 *
 * Flags parent nodes where a group of 2+ same-type children ALL have `props.key`
 * AND all key values in the group are non-negative integer strings — the signature
 * of `key={i}` in a `.map()` call.
 *
 * Why this matters: When the list order changes (insertions, deletions, reorders),
 * index-based keys cause React to incorrectly match new elements to old component
 * instances, producing stale state, missed animations, and unnecessary re-renders.
 *
 * This rule is complementary to `missing-key-prop` (no keys at all). It specifically
 * catches the case where keys are present but are generated from an array index.
 *
 * Detection logic (O(n) over children):
 *   - Group children by `type`
 *   - For each group with 2+ members where ALL have a `props.key`:
 *     - If every key value is a non-negative integer string → fire
 *
 * Node-level rule. O(n) per node. Pure function, no DOM, deterministic.
 */
export function createIndexAsKeyRule(): Rule {
  return {
    name: 'index-as-key',
    detect: (node: ComponentNode, _metrics: PerformanceMetrics): RuleResult => {
      const children = node.children
      if (!children || children.length < 2) {
        return { triggered: false }
      }

      // Group children by type
      const byType = new Map<string, ComponentNode[]>()
      for (const child of children) {
        const existing = byType.get(child.type)
        if (existing) {
          existing.push(child)
        } else {
          byType.set(child.type, [child])
        }
      }

      for (const [type, group] of byType) {
        if (group.length < 2) continue

        // All children in the group must have a key prop
        const allHaveKey = group.every(
          child => child.props !== undefined && child.props !== null && 'key' in child.props,
        )
        if (!allHaveKey) continue

        // All keys must be non-negative integer strings
        const allNumericKeys = group.every(child =>
          isNonNegativeIntegerString(child.props!['key']),
        )

        if (allNumericKeys) {
          return {
            triggered: true,
            issue: {
              rule: 'index-as-key',
              severity: 'warning',
              message: `${group.length} "${type}" children in "${node.id}" use numeric string keys — likely generated from an array index. Index keys cause incorrect component reuse on list reorder; use stable, unique IDs instead.`,
              nodeId: node.id,
            },
          }
        }
      }

      return { triggered: false }
    },
  }
}
